drop table mainvisual;
drop table mainpop;
drop table notice;
drop table notice_file;
drop table member;
drop table prbinfo;
drop table subsidiary;

CREATE TABLE MAINVISUAL(
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	DISP_YN VARCHAR(1) NOT NULL,
	LANG_KO_YN VARCHAR(1) NOT NULL,
	TITLE VARCHAR(300) NOT NULL,
	TYPE VARCHAR(1) NOT NULL,
	PC_IMG_PATH VARCHAR(500),
	PC_IMG_LINK VARCHAR(4000),
	MO_IMG_PATH VARCHAR(500),
	MO_IMG_LINK VARCHAR(4000),
	VIDEOS_URL VARCHAR(4000),
	VIDEOS_PATH VARCHAR(500),
	TOP_SUB_TXT VARCHAR(1200),
	BOTTOM_MAIN_TXT VARCHAR(2400),
	ORDER_SEQ INT,
	REG_ID INT,
	REG_DTIME DATETIME  DEFAULT CURRENT_TIMESTAMP,
	UPD_ID INT,
	UPD_DTIME DATETIME  DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MAINPOP(
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	DISP_YN VARCHAR(1) NOT NULL,
	LANG_KO_YN VARCHAR(1) NOT NULL,
	TITLE VARCHAR(300) NOT NULL,
	POP_IMG_PATH VARCHAR(500),
	POP_IMG_LINK VARCHAR(4000),
	POP_IMG_LINK_TARGET VARCHAR(10),
	WIDTH_POINT VARCHAR(5),
	HEIGHT_POINT VARCHAR(5),
	DISP_START_DAY VARCHAR(10),
	DISP_START_TIME VARCHAR(2),
	DISP_END_DAY VARCHAR(10),
	DISP_END_TIME VARCHAR(2),
	REG_ID INT,
	REG_DTIME DATETIME  DEFAULT CURRENT_TIMESTAMP,
	UPD_ID INT,
	UPD_DTIME DATETIME  DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE NOTICE(
	NOTICE_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	DISP_YN VARCHAR(1) NOT NULL,
	DISP_START_DAY VARCHAR(10),
	DISP_START_TIME VARCHAR(2),
	LANG_KO_YN VARCHAR(1) NOT NULL,
	TITLE VARCHAR(300) NOT NULL,
	CONTENT TEXT,
	REG_ID INT,
	REG_DTIME DATETIME  DEFAULT CURRENT_TIMESTAMP,
	UPD_ID INT,
	UPD_DTIME DATETIME  DEFAULT CURRENT_TIMESTAMP

);



CREATE TABLE NOTICE_FILE(
	FILE_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	FILE_NAME VARCHAR(300) NOT NULL,
	FILE_EXT VARCHAR(6) NOT NULL,
	FILE_PATH VARCHAR(500) NOT NULL,
	FILE_LENGTH VARCHAR(10) NOT NULL,
	REG_ID INT,
	REG_DTIME DATETIME  DEFAULT CURRENT_TIMESTAMP,
	UPD_ID INT,
	UPD_DTIME DATETIME  DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE MEMBER(
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	AUTH VARCHAR(10) DEFAULT 'ROLE_USER',
	LOGIN_ID VARCHAR(16) NOT NULL,
	NAME VARCHAR(150),
	PASSWORD TEXT,
	EMAIL_ID VARCHAR(50),
	EMAIL_DOMAIN VARCHAR(50),
	PNUM VARCHAR(13),
	RANK VARCHAR(30),
	USE_YN VARCHAR(1) DEFAULT 'Y',
	MAIN_AUTHORITY VARCHAR(1),
	NOTICE_AUTHORITY VARCHAR(1),
	LOGIN_DATE DATETIME,
	LOGIN_LOCK VARCHAR(1) DEFAULT 'N',
	LOGIN_CNT INT DEFAULT 0,
	REG_ID INT,
	REG_DTIME DATETIME  DEFAULT CURRENT_TIMESTAMP,
	UPD_ID INT,
	UPD_DTIME DATETIME  DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE SUBSIDIARY(
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	CODE VARCHAR(5),
	NAME VARCHAR(60),
	NAME_EN VARCHAR(120),
	URL VARCHAR(100),
	USE_YN VARCHAR(1) DEFAULT 'Y',
	ORDER_SEQ INT,
	REG_ID INT,
	REG_DTIME DATETIME  DEFAULT CURRENT_TIMESTAMP,
	UPD_ID INT,
	UPD_DTIME DATETIME  DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE PRBINFO(
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	CONTENT TEXT,
	USE_YN VARCHAR(1) DEFAULT 'Y',
	REG_ID INT,
	REG_DTIME DATETIME  DEFAULT CURRENT_TIMESTAMP,
	UPD_ID INT,
	UPD_DTIME DATETIME  DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE `QNA` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `division` varchar(1) CHARACTER SET latin1 NOT NULL COMMENT '구분',
  `username` varchar(300) NOT NULL COMMENT '작성자 이름',
  `phone` varchar(20) CHARACTER SET latin1 NOT NULL COMMENT '작성자 휴대폰 번호',
  `useremail` varchar(100) CHARACTER SET latin1 NOT NULL COMMENT '작성자 이메일주소',
  `usertitle` varchar(900) CHARACTER SET latin1 NOT NULL COMMENT '문의 제목',
  `usercontents` varchar(3000) CHARACTER SET latin1 NOT NULL COMMENT '문의 내용',
  `userfile` varchar(100) CHARACTER SET latin1 NOT NULL COMMENT '문의 내용 첨부 파일',
  `answer_date` varchar(30) COMMENT '답변 날짜',
  `answer_title` varchar(900) COMMENT '답변 제목',
  `answer_contents` text COMMENT '답변 내용',
  `send_email` varchar(50) COMMENT '이메일 전송',
  `reg_id` int(11) COMMENT '등록자',
  `reg_dtime` datetime DEFAULT current_timestamp() COMMENT '등록시간',
  `upd_id` int(11) COMMENT '수정자',
  `upd_dtime` datetime DEFAULT current_timestamp() COMMENT '수정시간',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='문의하기';


